services:
    hermit-purple:
        build:
            dockerfile: "./Dockerfile"
            tags:
                - "weebify/hermit-purple:latest"
        ports:
            - "127.0.0.1:3000:3000"
        environment:
          PORT: 3000
          VALKEY_URL: valkey://valkey:6379
    valkey:
        image: valkey/valkey:8.1.3-alpine
        expose:
            - 6379
